### ISSUE TITLE
only one error is shown at a time when calling `validate`

### ISSUE THREAD

**Issue by vemoo** [CodeStix/typed-react-form#2]
See: https://codesandbox.io/s/charming-feistel-4ih65?file=/src/App.tsx
You have to click submit two times for both errors to appear. 

I think the issue is that here https://github.com/CodeStix/typed-react-form/blob/9b8647d8a08827effd4599dd12dd9b5c10ef40d3/src/form.ts#L356-L364 if `changed` is `true` `setError` is not called.

I guess it's like this to avoid setting all errors when one field changes. One option I can think of is for it to behave differently if it's called from `validate`.

**Comment by CodeStix** [comment]
Yup, you are right, I totally overlooked that. Thanks!
